### ISSUE TITLE
Отсутствие проверки на отрицательное значение начального баланса кредитного счета

### ISSUE THREAD

**Issue by ischeglov** [ischeglov/HW_TeamProject#1]
# Описание
В конструкторе класса CreditAccount отсутствует проверка параметра initialBalance (начального баланса) на отрицательное значение и выброса исключения IllegalArgumentException

# Локация дефекта

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Создать объект класса CreditAccount с отрицательным значением initialBalance, остальные параметры могут быть корректными

Params:<br>
| initialBalance          | creditLimit      | rate |
| ------------- | --------- | -------- |
| -1000       | 5000   | 20        |

<br>

*Ожидаемый результат:* Выброс исключения IllegalArgumentException
*Фактический результат:* Создается объект класса CreditAccount с отрицательным значением initialBalance

# Тест

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L29

# Скриншот
<img width="1370" alt="Снимок экрана 2024-05-19 в 20 18 56" src="https://github.com/ischeglov/HW_TeamProject/assets/127974199/cc082e17-b85e-494b-a1b5-75e61e510431">

# Окружение
* **Операционная система:** macOS Sonoma 14.5 (23F79)
* **IDE:** IntelliJ IDEA 2024.1.1 (Ultimate Edition) 
* **Java:** OpenJDK 11.0.23

**Comment by NadezhdaT87** [comment]
fix
