### ISSUE TITLE
Некорректное обновление баланса при пополнении сберегательного счета в методе add класса SavingAccount 

### ISSUE THREAD

**Issue by NadezhdaT87** [ischeglov/HW_TeamProject#12]
# Описание
Реализация метода add в классе SavingAccount  не учитывает текущий баланс и присваивает значение amount (сумма пополнения) параметру balance
# Локация дефекта
https://github.com/ischeglov/HW_TeamProject/blob/6e3019dfc129a91fa330908bb35624b6264a7b50/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68-L76

# Шаги воспроизведения
1. Создать объект класса SavingAccount со следующими параметрами:
initialBalance = 2000
minBalance = 1000
maxBalance = 10 000
rate = 10
1. Вызвать метод add со значением amount равным 3000

*Ожидаемый результат:* текущее значение баланса 5000
*Фактический результат:* текущее значение баланса 3000

# Тест
https://github.com/ischeglov/HW_TeamProject/blob/ef85e62c4fe48a889203a7dad38b6721b37d3974/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L35-L46

# Скриншот
![add1](https://github.com/ischeglov/HW_TeamProject/assets/162036733/31d2b339-9e22-471c-91c8-8e0ac7e253cd)

# Окружение
* **Операционная система:** Windows 11, version 23H2
* **IDE:** IntelliJ IDEA 2023.3.6 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ischeglov** [comment]
fix
