### ISSUE TITLE
Некорректное обновление баланса при покупке со сберегательного счета в методе pay класса SavingAccount при большей суммы покупки, чем суммы текущего баланса 

### ISSUE THREAD

**Issue by NadezhdaT87** [ischeglov/HW_TeamProject#13]
# Описание
Реализация метода pay в классе SavingAccount не учитывает текущий баланс при покупке в рамках установленного кредитного лимита
# Локация дефекта
https://github.com/ischeglov/HW_TeamProject/blob/6e3019dfc129a91fa330908bb35624b6264a7b50/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L54

# Шаги воспроизведения
1. Создать объект класса SavingAccount со следующими параметрами:
initialBalance = 5000
minBalance = 0
maxBalance = 10 000
rate = 10
1. Вызвать метод pay со значением amount равным 6000

*Ожидаемый результат:* текущее значение баланса 5000
*Фактический результат:* текущее значение баланса -1000

# Тест
https://github.com/ischeglov/HW_TeamProject/blob/ef85e62c4fe48a889203a7dad38b6721b37d3974/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L91-L102

# Скриншот
![pay1](https://github.com/ischeglov/HW_TeamProject/assets/162036733/7e6ff926-f224-4079-b3d1-4e9e6296c30a)

# Окружение
* **Операционная система:** Windows 11, version 23H2
* **IDE:** IntelliJ IDEA 2023.3.6 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ischeglov** [comment]
fix
