### ISSUE TITLE
Некорректное обновление баланса при покупке со сберегательного счета в методе pay класса SavingAccount не превышающей суммы текущего баланса

### ISSUE THREAD

**Issue by NadezhdaT87** [ischeglov/HW_TeamProject#14]
# Описание
Реализация метода pay в классе SavingAccount не учитывает минимальный баланс при покупке в рамках установленного минимального и максимального баланса
# Локация дефекта
https://github.com/ischeglov/HW_TeamProject/blob/6e3019dfc129a91fa330908bb35624b6264a7b50/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L54

# Шаги воспроизведения
1. Создать объект класса SavingAccount со следующими параметрами:
initialBalance = 5000
minBalance = 2000
maxBalance = 10 000
rate = 10
1. Вызвать метод pay со значением amount равным 4000

*Ожидаемый результат:* текущее значение баланса 5000
*Фактический результат:* текущее значение баланса 1000

# Тест
https://github.com/ischeglov/HW_TeamProject/blob/ef85e62c4fe48a889203a7dad38b6721b37d3974/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L105-L116

# Скриншот
![pay2](https://github.com/ischeglov/HW_TeamProject/assets/162036733/be2c3ef8-231b-4483-8102-428569203dc6)

# Окружение
* **Операционная система:** Windows 11, version 23H2
* **IDE:** IntelliJ IDEA 2023.3.6 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ischeglov** [comment]
fix
