### ISSUE TITLE
Некорректное обновление баланса при пополнении кредитного счета в методе add класса CreditAccount

### ISSUE THREAD

**Issue by ischeglov** [ischeglov/HW_TeamProject#3]
# Описание
Реализация метода add в классе CreditAccount не учитывает текущий баланс и присваивает значение amount (сумма пополнения) параметру balance

# Локация дефекта

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65-L71

# Шаги воспроизведения
1. Создать объект класса CreditAccount со следующими параметрами:

Params:<br>
| initialBalance          | creditLimit      | rate |
| ------------- | --------- | -------- |
| 1000       | 5000   | 15        |

<br>

 2. Вызвать метод add со значением amount равным 3000

*Ожидаемый результат:* текущее значение баланса 4000
*Фактический результат:* текущее значение баланса 3000

# Тест

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35-L44

# Скриншот
<img width="1314" alt="Снимок экрана 2024-05-19 в 20 59 38" src="https://github.com/ischeglov/HW_TeamProject/assets/127974199/47903314-2c10-419f-b59b-3728a43420bf">

# Окружение
* **Операционная система:** macOS Sonoma 14.5 (23F79)
* **IDE:** IntelliJ IDEA 2024.1.1 (Ultimate Edition) 
* **Java:** OpenJDK 11.0.23

**Comment by NadezhdaT87** [comment]
fix
