### ISSUE TITLE
Некорректное обновление баланса при покупке с кредитного счета в методе pay класса CreditAccount в рамках установленного кредитного лимита

### ISSUE THREAD

**Issue by ischeglov** [ischeglov/HW_TeamProject#4]
# Описание
Реализация метода pay в классе CreditAccount не учитывает текущий баланс при покупке в рамках установленного кредитного лимита

# Локация дефекта

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L51

# Шаги воспроизведения
1. Создать объект класса CreditAccount со следующими параметрами

Params:<br>
| initialBalance          | creditLimit      | rate |
| ------------- | --------- | -------- |
| 1000       | 5000   | 15        |

<br>

 2. Вызвать метод pay со значением amount равным 5000

*Ожидаемый результат:* текущее значение баланса -4000
*Фактический результат:* текущее значение баланса -5000

# Тест

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L74-L83

# Скриншот
<img width="1330" alt="Снимок экрана 2024-05-19 в 22 31 54" src="https://github.com/ischeglov/HW_TeamProject/assets/127974199/af5db3ce-2685-48ef-80e7-2e29390f1380">

# Окружение
* **Операционная система:** macOS Sonoma 14.5 (23F79)
* **IDE:** IntelliJ IDEA 2024.1.1 (Ultimate Edition) 
* **Java:** OpenJDK 11.0.23

**Comment by NadezhdaT87** [comment]
fix
