### ISSUE TITLE
Некорректное обновление баланса при покупке с кредитного счета в методе pay класса CreditAccount при превышении кредитного лимита

### ISSUE THREAD

**Issue by ischeglov** [ischeglov/HW_TeamProject#5]
# Описание
Реализация метода pay в классе CreditAccount не учитывает кредитный лимит при покупке

# Локация дефекта

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L51

# Шаги воспроизведения
1. Создать объект класса CreditAccount со следующими параметрами

Params:<br>
| initialBalance          | creditLimit      | rate |
| ------------- | --------- | -------- |
| 1000       | 5000   | 15        |

<br>

 2. Вызвать метод pay со значением amount равным 7000

*Ожидаемый результат:* текущее значение баланса 1000
*Фактический результат:* текущее значение баланса -6000

# Тест

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L87-L96

# Скриншот

<img width="1273" alt="Снимок экрана 2024-05-19 в 23 48 12" src="https://github.com/ischeglov/HW_TeamProject/assets/127974199/6e69a08e-69b6-4d19-888f-06305f214e2a">

# Окружение
* **Операционная система:** macOS Sonoma 14.5 (23F79)
* **IDE:** IntelliJ IDEA 2024.1.1 (Ultimate Edition) 
* **Java:** OpenJDK 11.0.23

**Comment by NadezhdaT87** [comment]
fix
