### ISSUE TITLE
Некорректный расчет процентов баланса кредитного счета в методе yearChange класса CreditAccount 

### ISSUE THREAD

**Issue by ischeglov** [ischeglov/HW_TeamProject#6]
# Описание
Реализация метода yearChange в классе CreditAccount не учитывает положительный баланс счета, при котором не должны начисляться проценты
# Локация дефекта

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L84

# Шаги воспроизведения
1. Создать объект класса CreditAccount со следующими параметрами

Params:<br>
| initialBalance          | creditLimit      | rate |
| ------------- | --------- | -------- |
| 200       | 5000   | 15        |

<br>

 2. Вызвать метод yearChange

*Ожидаемый результат:* метод возвращает значение 0
*Фактический результат:* метод возвращает значение 30

# Тест

https://github.com/ischeglov/HW_TeamProject/blob/5f21eeda88e79cc564480abb9aa8ffe013fe4172/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L111-L125

# Скриншот

<img width="1303" alt="Снимок экрана 2024-05-20 в 00 04 35" src="https://github.com/ischeglov/HW_TeamProject/assets/127974199/6fe336eb-56a5-423f-8e57-09a21eb1b921">

# Окружение
* **Операционная система:** macOS Sonoma 14.5 (23F79)
* **IDE:** IntelliJ IDEA 2024.1.1 (Ultimate Edition) 
* **Java:** OpenJDK 11.0.23

**Comment by NadezhdaT87** [comment]
fix
