### ISSUE TITLE
Отсутствие проверки на отрицательное значение минимального баланса сберегательного счета

### ISSUE THREAD

**Issue by NadezhdaT87** [ischeglov/HW_TeamProject#8]
# Описание
В конструкторе класса SavingAccount отсутствует проверка параметра minBalance (минимального баланса) на отрицательное значение и выброса исключения IllegalArgumentException

# Локация дефекта
https://github.com/ischeglov/HW_TeamProject/blob/4074fdd4c614a755a2f20e0c27482d2493423922/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
Создать объект класса SavingAccount с отрицательным значением initialBalance, остальные параметры могут быть корректными
initialBalance = 0
minBalance = -1000
maxBalance = 5000
rate = 10

*Ожидаемый результат:* Выброс исключения IllegalArgumentException
*Фактический результат:* Создается объект класса SavingAccount с отрицательным значением minBalance

# Скриншот
![Снимок экрана 2024-05-23 150133](https://github.com/ischeglov/HW_TeamProject/assets/162036733/5e20a2bd-df58-4d5c-8929-84ee8e4464b2)

# Окружение
* **Операционная система:** Windows 11, version 23H2
* **IDE:** IntelliJ IDEA 2023.3.6 (Community Edition)
* **Java:** OpenJDK 11

**Comment by ischeglov** [comment]
fix
